import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/components/AuthContext";
import { Providers } from "@/components/providers";
import { cookies } from "next/headers";
import ClientWrapper from "@/components/ClientWrapper";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const themeCookie = cookiesStore.get("theme")?.value;
  const theme = themeCookie === "dark" ? "dark" : "light";


  return (
    <html lang="en"
      className={cn("font-mono", jetbrainsMono.variable, theme)}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <AuthProvider>
          <Providers defaultTheme={theme}>
            <div className="flex min-h-screen">
              <ClientWrapper>
                {children}
              </ClientWrapper>
            </div>

          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
